[env:nodemcu-32s]
platform = espressif32@6.7.0
board = nodemcu-32s
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    rfetick/MPU6050_light
    https://github.com/aed3/PS4-esp32.git
